# Generated by Django 5.2.5 on 2025-08-20 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=20)),
                ('duration_weeks', models.PositiveSmallIntegerField(default=4)),
                ('prerequisites_json', models.JSONField(default=list)),
                ('learning_outcomes_json', models.JSONField(default=list)),
                ('capstone', models.TextField()),
                ('references_json', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('objectives_json', models.JSONField(default=list)),
                ('lessons', models.PositiveSmallIntegerField(default=2)),
                ('quiz_items', models.PositiveSmallIntegerField(default=5)),
                ('project', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='api.course')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('course', 'order')},
            },
        ),
    ]
